### ISSUE TITLE
Themes - Dark Mode

### ISSUE THREAD

**Issue by DaveJarvis** [DaveJarvis/keenwrite#66]
Provide the ability to use themes. In particular a dark mode. [Markdown-Writer-FX](https://github.com/JFormDesigner/markdown-writer-fx) may have examples of skinning the application.

# Technical

The `createScene` method in `MainScene.java` sets the stylesheet theme.

User should have ability to switch between themes or create their own customized theme. Existing themes (also, see attached files):

* [Modena](https://github.com/joffrey-bion/javafx-themes/blob/master/css/modena_dark.css)
* [Recaf](https://github.com/Col-E/Recaf/blob/master/src/main/resources/style/ui-dark.css)
* [Sakura Solarized](https://github.com/oxalorg/sakura/blob/master/css/sakura-dark-solarized.css)
* [Charcoal](https://www.iditect.com/how-to/53689381.html)

See also: https://stackoverflow.com/a/42541771/59087

## User Preferences

Include ability to change font size (in **em**, relative to **1em**) and base application colours, such as those from Joffrey Bion's [Modena dark theme](https://github.com/joffrey-bion/javafx-themes/blob/master/css/modena_dark.css). This will require adding a new set of keys to the workspace to cover the following:

``` css
.root {
  -fx-font-size: .8em;

  -fx-base: rgb(50, 50, 50);
  -fx-background: rgb(50, 50, 50);

  /* Lighter controls (buttons, thumb, etc.) */
  -fx-color: derive(-fx-base, 10%);

  /* Text field and table row */
  -fx-control-inner-background: rgb(20, 20, 20);
  /* Alternating rows */
  -fx-control-inner-background-alt: derive(-fx-control-inner-background, 2.5%);

  /* Text colours */
  -fx-light-text-color: rgb(220, 220, 220);
  -fx-mid-text-color: rgb(100, 100, 100);
  -fx-dark-text-color: rgb(20, 20, 20);

  /* Accent colour (selected items, progress bars, text highlights) */
  -fx-accent: rgb(0, 80, 100);

  /* Non-focused, but selected elements */
  -fx-selection-bar-non-focused: rgb(50, 50, 50);
}
```

The scroll bar button arrow colours can probably derive from the `-fx-light-text-color`:

``` css
.scroll-bar > .increment-button > .increment-arrow,
.scroll-bar > .decrement-button > .decrement-arrow {
    -fx-background-color: -fx-mark-highlight-color, rgb(220, 220, 220);
}

.scroll-bar > .increment-button:hover > .increment-arrow,
.scroll-bar > .decrement-button:hover > .decrement-arrow {
    -fx-background-color: -fx-mark-highlight-color, rgb(240, 240, 240);
}

.scroll-bar > .increment-button:pressed > .increment-arrow,
.scroll-bar > .decrement-button:pressed > .decrement-arrow {
    -fx-background-color: -fx-mark-highlight-color, rgb(255, 255, 255);
}
```

Store RGB values as six-character hex codes without leading hash.
